config/routes.rb
Rails.application.routes.draw do

  # 管理者用
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    resources :members, only: [:index, :show, :edit, :update]
    get '/', to: 'homes#top', as: 'top'
    resources :books, only: [:show, :index, :destroy] do
      resources :post_comments, only: [:destroy]
    end
    resources :genres, only: [:index, :edit, :update, :destroy]
  end

  # 顧客用
  devise_for :members,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_scope :member do
    post 'members/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  scope module: :public do
    root :to =>"homes#top"

    get 'home/about', to: 'homes#about', as: 'about'

    get 'home/terms_of_use', to: 'homes#terms_of_use', as: 'terms_of_use'

    get 'members/unsubscribe', to: 'members#unsubscribe', as: 'confirm_unsubscribe'
    patch 'members/withdraw', to: 'members#withdraw', as: 'withdraw_member'

    resources :members, only: [:index,:show,:edit,:update] do
      resource :relationships, only: [:create, :destroy]
    	get 'followings', to: 'relationships#followings', as: 'followings'
    	get 'followers', to: 'relationships#followers', as: 'followers'
    	member do
        get :favorites
      end
    end

    get 'books/search'
    get 'books/selection'
    resources :books, only: [:new, :index, :show, :edit, :create, :destroy, :update] do
      resources :post_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end

    get '/search', to: 'searches#search'

  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :member
  belongs_to :genre

  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  enum status: { public: 0, private: 1 }, _suffix: true

  validates :catchphrase, length:{maximum:50}
  validates :body, length:{maximum:250}

  def favorited_by?(member)
    favorites.where(member_id: member.id).exists?
    favorites.exists?(member_id: member.id)
  end

  def self.search_for(content, method, column)
    if method == 'perfect'
      members =  Book.where("#{column} LIKE?","#{content}").where(status: :public)
      return members
    elsif method == 'forward'
      Book.where("#{column} LIKE ?", "#{content}" + '%').where(status: :public)
    elsif method == 'backward'
      Book.where("#{column} LIKE ?", '%' + "#{content}").where(status: :public)
    else
      Book.where("#{column} LIKE ?", '%' + "#{content}" + '%').where(status: :public)
    end
  end

end

app/controllers/admin/books_controller.rb
class Admin::BooksController < ApplicationController
   before_action :admin_signed_in, only: [:show, :destroy]


  def show
    @book = Book.find(params[:id])
    @post_comment = PostComment.new
    @post_comments = @book.post_comments.page(params[:page]).per(9)
  end

  def index
    @books = Book.where(status: :public).page(params[:page]).per(9)
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to admin_books_path
  end

  private

  def admin_signed_in
    unless admin_signed_in?
      redirect_to new_admin_session_path
    end
  end

  def book_params
    params.require(:book).permit(:member_id, :genre_id, :isbn, :title, :image_url, :author, :publisher_name, :catchphrase, :body, :status)
  end

  def post_comment_params
    params.require(:post_comment).permit(:comment)
  end

end

app/helpers/admin/books_helper.rb
module Admin::BooksHelper
end

app/views/admin/books/_image_url.html.erb
<% if book.image_url %>
  <%= image_tag book.image_url, size:"210x260", class: "image img-fluid" %>
<% else %>
  <%= image_tag "no_image.jpg", size:"210x260",  class: "image img-fluid" %>
<% end %>

app/views/admin/books/_index.html.erb
<% books.each do |book| %>
  <div class="col-12 col-md-4 mt-3 mp-3">
    <div class="card" >
      <div class="bd-placeholder-img card-img-top card-center" width="100%" height="180">
        <%= link_to admin_book_path(book.id) do %>
          <%= render "admin/books/image_url", book: book %>
        <% end %>
      </div>
      <div class="card-body">
        <p class="card-text card-color">投稿者:<br>
          <%= link_to admin_member_path(book.member_id), class: "link" do %>
            <%= book.member.nick_name %>
          <% end %>
        </p>
        <h6 class="card-title card-color">タイトル:<br><%= link_to book.title, admin_book_path(book.id), class: "link" %></h6>
        <p class="card-text card-color">ジャンル:<br><%= book.genre.name %></p>
        <p class="card-text card-color">キャッチコピー:<br><%= book.catchphrase %></p>
        <% if member_signed_in? %>
          <div class="card-color" id="favorite_buttons_<%= book.id %>">ブックマーク:<br><%= render "public/favorites/btn", book: book %></div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

<% for num in 1..(3-(books.length % 3)) %>
  <div class="col-12 col-md-4"></div>
<% end %>

app/views/admin/books/index.html.erb
<div class='container'>
  <h2 class="pt-3" style="text-align: center;">投稿一覧</h2>
	<div class='row justify-content-center pt-3'>
    <%= render "admin/books/index", books: @books %>
    <div class="mt-2">
      <%= paginate @books %>
    </div>
  </div>
</div>

app/views/admin/books/show.html.erb
<div class='container pb-5'>
	<div class='row justify-content-center pt-3'>
		<h2 class="col-md-auto section-ttl text-center">投稿詳細</h2>
	</div>
	<div class='row justify-content-center pt-5'>
    <div class="col-md-3 px-4 mx-0">
      <% if @book.image_url %>
        <%= image_tag @book.image_url, size:"240x300", class: "image img-fluid" %>
      <% else %>
        <%= image_tag "no_image.jpg", size:"240x300",  class: "image img-fluid" %>
      <% end %>
    </div>
    <div class="col-md-9 px-0 mx-0">
      <table class='table border-danger'>
        <tr>
          <th class="text-nowrap">タイトル</th>
          <td class="tb_color"><%= @book.title %></td>
        </tr>
        <tr>
          <th class="text-nowrap">著者</th>
          <td class="tb_color"><%= @book.author %></td>
        </tr>
        <tr>
          <th class="text-nowrap">出版社</th>
          <td class="tb_color"><%= @book.publisher_name %></td>
        </tr>
        <tr>
          <th class="text-nowrap">ジャンル</th>
          <td class="tb_color"><%= @book.genre.name %></td>
        </tr>
        <tr>
          <th class="text-nowrap">キャッチコピー</th>
          <td class="tb_color"><%= @book.catchphrase %></td>
        </tr>
      </table>
    </div>
  </div>
  <div class='row pt-1 justify-content-center'>
    <div class="col-md-3 text-center status-color">
      <div>ステータス:
        <% if @book.public_status? %>
          <span class="text-public">公開</span>
        <% else %>
          <span class="text-private">非公開</span>
        <% end %>
      </div>
      <div class='justify-content-center'>
        <td><%= link_to '削除', admin_book_path(@book), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger mx-2 my-2" %></td>
      </div>
    </div>
    <div class="col-md-9 text-cenet justify-content-center">
		  <h5 class="text-center">紹介文</h5>
		  <div class="text-break book-body">
        <p class="text-center"><%= @book.body %></p>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="col-md-8 mx-auto text-center">
    <h4>コメント一覧</h4>
    <div class='book-comments-area'>
      <%= render "admin/post_comments/index", post_comments: @post_comments %>
    </div>
    <div id="comment-paginate">
      <%= paginate @post_comments %>
    </div>
  </div>
</div>