config/routes.rb
Rails.application.routes.draw do

  # 管理者用
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    resources :members, only: [:index, :show, :edit, :update]
    get '/', to: 'homes#top', as: 'top'
    resources :books, only: [:show, :index, :destroy] do
      resources :post_comments, only: [:destroy]
    end
    resources :genres, only: [:index, :edit, :update, :destroy]
  end

  # 顧客用
  devise_for :members,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_scope :member do
    post 'members/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  scope module: :public do
    root :to =>"homes#top"

    get 'home/about', to: 'homes#about', as: 'about'

    get 'home/terms_of_use', to: 'homes#terms_of_use', as: 'terms_of_use'

    get 'members/unsubscribe', to: 'members#unsubscribe', as: 'confirm_unsubscribe'
    patch 'members/withdraw', to: 'members#withdraw', as: 'withdraw_member'

    resources :members, only: [:index,:show,:edit,:update] do
      resource :relationships, only: [:create, :destroy]
    	get 'followings', to: 'relationships#followings', as: 'followings'
    	get 'followers', to: 'relationships#followers', as: 'followers'
    	member do
        get :favorites
      end
    end

    get 'books/search'
    get 'books/selection'
    resources :books, only: [:new, :index, :show, :edit, :create, :destroy, :update] do
      resources :post_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end

    get '/search', to: 'searches#search'

  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :books, dependent: :destroy

  def self.search_for(content, method)
    if method == 'perfect'
      Genre.where(name: content)
    elsif method == 'forward'
      Genre.where('name LIKE ?', content+'%')
    elsif method == 'backward'
      Genre.where('name LIKE ?', '%'+content)
    else
      Genre.where('name LIKE ?', '%'+content+'%')
    end
  end

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!

  def index
    @genre = Genre.new
    @genres = Genre.all.page(params[:page]).per(10)
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path, notice: "編集成功しました"
    else
      render "edit", notice: "編集失敗しました"
    end
  end

  def destroy
    @genre = Genre.find(params[:id])
    @genre.destroy
    redirect_to admin_genres_path
  end

  private

  def ensure_genre
    @genre = Genre.find(params[:id])
  end

  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/views/admin/genres/edit.html.erb
<div class='container pb-5'>
  <div class='row justify-content-center pt-3'>
    <h2 class="col-md-auto section-ttl text-center">編集画面</h2>
  </div>
  <%= form_with model: @genre, url: admin_genre_path(@genre),local:true do |f| %>
    <div class="col-md-10 col-lg-7 px-5 px-sm-0 mx-auto">
      <table class="table">
        <tr>
          <td class="tb_color"><%= @genre.name %></td>
          <%= f.text_field :name, class: "form-control name" %>
        </tr>
      </table>
      <div class="text-center">
        <%= link_to '戻る', admin_genres_path(@genre.id), class: "btn btn-secondary mx-4" %>
        <%= f.submit '保存', class: "btn btn-success mx-4" %>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/genres/index.html.erb
<div class='container pb-5'>
	<div class='row justify-content-center pt-5'>
		<h3 class="col-md-auto section-ttl text-center">ジャンル一覧</h3>
	</div>
	<div class='row'>
		<div class="col-md-auto px-5 mx-auto mt-4">
			<table>
				<thead>
					<tr>
						<th class='text-center'>ジャンル名</th>
						<th></th>
					</tr>
				</thead>
				<tbody>
					<% @genres.each do |genre| %>
						<tr>
							<td class="tb_color"><%= genre.name %></td>
							<td><%= link_to '編集', edit_admin_genre_path(genre), class: "btn btn-sm btn-success mx-2 my-2" %></td>
							<td class='text-center text-nowrap pl-3'><%= link_to '削除', admin_genre_path(genre), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger my-1" %></td>
						</tr>
					<% end %>
				</tbody>
			</table>
			<%= paginate @genres %>
		</div>
	</div>
</div>