config/routes.rb
Rails.application.routes.draw do

  # 管理者用
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    resources :members, only: [:index, :show, :edit, :update]
    get '/', to: 'homes#top', as: 'top'
    resources :books, only: [:show, :index, :destroy] do
      resources :post_comments, only: [:destroy]
    end
    resources :genres, only: [:index, :edit, :update, :destroy]
  end

  # 顧客用
  devise_for :members,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_scope :member do
    post 'members/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  scope module: :public do
    root :to =>"homes#top"

    get 'home/about', to: 'homes#about', as: 'about'

    get 'home/terms_of_use', to: 'homes#terms_of_use', as: 'terms_of_use'

    get 'members/unsubscribe', to: 'members#unsubscribe', as: 'confirm_unsubscribe'
    patch 'members/withdraw', to: 'members#withdraw', as: 'withdraw_member'

    resources :members, only: [:index,:show,:edit,:update] do
      resource :relationships, only: [:create, :destroy]
    	get 'followings', to: 'relationships#followings', as: 'followings'
    	get 'followers', to: 'relationships#followers', as: 'followers'
    	member do
        get :favorites
      end
    end

    get 'books/search'
    get 'books/selection'
    resources :books, only: [:new, :index, :show, :edit, :create, :destroy, :update] do
      resources :post_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end

    get '/search', to: 'searches#search'

  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post_comment.rb
class PostComment < ApplicationRecord

  belongs_to :member
  belongs_to :book

  validates :comment, presence: true, length:{maximum:50}

end

app/controllers/admin/post_comments_controller.rb
class Admin::PostCommentsController < ApplicationController

  def destroy
    book = Book.find(params[:book_id])
    @comment = PostComment.find(params[:id])
    @comment.destroy
    @post_comments = book.post_comments.page(params[:page]).per(10)
  end

  private

  def post_comment_params
    params.require(:post_comment).permit(:comment)
  end

end

app/helpers/admin/post_comments_helper.rb
module Admin::PostCommentsHelper
end

app/views/admin/post_comments/_index.html.erb
<% post_comments.each do |post_comment| %>
  <div class="row comment-body">
    <div class="col-md-3">
      <%= post_comment.member.nick_name %>
      <div class="mt-3">
        <%= link_to "削除", admin_book_post_comment_path(post_comment.book_id, post_comment), method: :delete, class: "btn btn-sm btn-danger pull-right ", remote: true %>
      </div>
    </div>
    <div class="col-md-9 text-break">
      <%= simple_format(post_comment.comment) %>
    </div>
  </div>
  <hr>
<% end %>

app/views/admin/post_comments/_show.html.erb
<table>
  <tbody>
      <% book.post_comments.each do |post_comment| %>
        <tr>
          <td>
            <%= link_to member_path(post_comment.member) do %>
              <%= image_tag post_comment.member.get_profile_image, size: "100x100" %><br>
              <%= post_comment.member.name %>
            <% end %>
          </td>
          <td><%= post_comment.comment %></td>
          <td>
            <% if post_comment.member == current_member %>
              <%= link_to "削除", book_post_comment_path(book, post_comment), method: :delete, class: "btn btn-danger pull-right", remote: true %>
            <% end %>
          </td>
        </tr>
      <% end %>
  </tbody>
</table>

app/views/admin/post_comments/create.js.erb
<% if @comment.errors.any? %>
  $('.error').text('コメント投稿に失敗しました。内容を確認してください。')
<% else %>
  $('.error').text('')
<% end %>
$('.comment-textarea').val("")
$('.book-comments-area').html("<%= j(render 'admin/post_comments/index', post_comments: @post_comments) %>")
$('#comment-paginate').html("<%= j(paginate @post_comments) %>")

app/views/admin/post_comments/destroy.js.erb
$('.book-comments-area').html("<%= j(render 'admin/post_comments/index', post_comments: @post_comments) %>")
$('#comment-paginate').html("<%= j(paginate @post_comments) %>")