config/routes.rb
Rails.application.routes.draw do

  # 管理者用
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    resources :members, only: [:index, :show, :edit, :update]
    get '/', to: 'homes#top', as: 'top'
    resources :books, only: [:show, :index, :destroy] do
      resources :post_comments, only: [:destroy]
    end
    resources :genres, only: [:index, :edit, :update, :destroy]
  end

  # 顧客用
  devise_for :members,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_scope :member do
    post 'members/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  scope module: :public do
    root :to =>"homes#top"

    get 'home/about', to: 'homes#about', as: 'about'

    get 'home/terms_of_use', to: 'homes#terms_of_use', as: 'terms_of_use'

    get 'members/unsubscribe', to: 'members#unsubscribe', as: 'confirm_unsubscribe'
    patch 'members/withdraw', to: 'members#withdraw', as: 'withdraw_member'

    resources :members, only: [:index,:show,:edit,:update] do
      resource :relationships, only: [:create, :destroy]
    	get 'followings', to: 'relationships#followings', as: 'followings'
    	get 'followers', to: 'relationships#followers', as: 'followers'
    	member do
        get :favorites
      end
    end

    get 'books/search'
    get 'books/selection'
    resources :books, only: [:new, :index, :show, :edit, :create, :destroy, :update] do
      resources :post_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end

    get '/search', to: 'searches#search'

  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :member
  belongs_to :genre

  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  enum status: { public: 0, private: 1 }, _suffix: true

  validates :catchphrase, length:{maximum:50}
  validates :body, length:{maximum:250}

  def favorited_by?(member)
    favorites.where(member_id: member.id).exists?
    favorites.exists?(member_id: member.id)
  end

  def self.search_for(content, method, column)
    if method == 'perfect'
      members =  Book.where("#{column} LIKE?","#{content}").where(status: :public)
      return members
    elsif method == 'forward'
      Book.where("#{column} LIKE ?", "#{content}" + '%').where(status: :public)
    elsif method == 'backward'
      Book.where("#{column} LIKE ?", '%' + "#{content}").where(status: :public)
    else
      Book.where("#{column} LIKE ?", '%' + "#{content}" + '%').where(status: :public)
    end
  end

end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :member
  belongs_to :book

  validates_uniqueness_of :book_id, scope: :member_id

end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :books, dependent: :destroy

  def self.search_for(content, method)
    if method == 'perfect'
      Genre.where(name: content)
    elsif method == 'forward'
      Genre.where('name LIKE ?', content+'%')
    elsif method == 'backward'
      Genre.where('name LIKE ?', '%'+content)
    else
      Genre.where('name LIKE ?', '%'+content+'%')
    end
  end

end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def self.guest
    find_or_create_by!(name: 'guest' ,email: 'guest@example.com') do |member|
      member.password = SecureRandom.urlsafe_base64
      member.name = "guest"
      member.nick_name = "guest"
      member.self_introduction = "guestです、よろしくお願いします"
      member.is_deleted = "false"
    end
  end

  has_one_attached :profile_image

  has_many :books, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower

  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed

  validates :name, presence: true, length:{maximum:50}
  validates :email, presence: true, uniqueness: true
  validates :nick_name, presence: true, length:{maximum:50}
  validates :self_introduction, length:{maximum:250}

  def follow(member)
    relationships.create(followed_id: member.id)
  end

  def unfollow(member)
    relationships.find_by(followed_id: member.id).destroy
  end

  def following?(member)
    followings.include?(member)
  end

  def self.search_for(content, method, column)
    if method == 'perfect'
      members =  Member.where("#{column} LIKE?","#{content}").where(is_deleted: :false)
      return members
    elsif method == 'forward'
      Member.where("#{column} LIKE ?", "#{content}" + '%').where(is_deleted: :false)
    elsif method == 'backward'
      Member.where("#{column} LIKE ?", '%' + "#{content}").where(is_deleted: :false)
    else
      Member.where("#{column} LIKE ?", '%' + "#{content}" + '%').where(is_deleted: :false)
    end
  end

end

app/models/post_comment.rb
class PostComment < ApplicationRecord

  belongs_to :member
  belongs_to :book

  validates :comment, presence: true, length:{maximum:50}

end

app/models/relationship.rb
class Relationship < ApplicationRecord

  belongs_to :follower, class_name: "Member"
  belongs_to :followed, class_name: "Member"

end

app/controllers/admin/books_controller.rb
class Admin::BooksController < ApplicationController
   before_action :admin_signed_in, only: [:show, :destroy]


  def show
    @book = Book.find(params[:id])
    @post_comment = PostComment.new
    @post_comments = @book.post_comments.page(params[:page]).per(9)
  end

  def index
    @books = Book.where(status: :public).page(params[:page]).per(9)
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to admin_books_path
  end

  private

  def admin_signed_in
    unless admin_signed_in?
      redirect_to new_admin_session_path
    end
  end

  def book_params
    params.require(:book).permit(:member_id, :genre_id, :isbn, :title, :image_url, :author, :publisher_name, :catchphrase, :body, :status)
  end

  def post_comment_params
    params.require(:post_comment).permit(:comment)
  end

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!

  def index
    @genre = Genre.new
    @genres = Genre.all.page(params[:page]).per(10)
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path, notice: "編集成功しました"
    else
      render "edit", notice: "編集失敗しました"
    end
  end

  def destroy
    @genre = Genre.find(params[:id])
    @genre.destroy
    redirect_to admin_genres_path
  end

  private

  def ensure_genre
    @genre = Genre.find(params[:id])
  end

  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController

  def top
    redirect_to admin_books_path
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/books_helper.rb
module Admin::BooksHelper
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/members_helper.rb
module Admin::MembersHelper
end

app/helpers/admin/post_comments_helper.rb
module Admin::PostCommentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_admin_footer.html.erb
<footer>
  <div class='container pt-2'>
    <div class='row'>
      <div class="col-auto mt-2 mx-auto">
        <h5 class="footer">Popularize a Books</h5>
      </div>
    </div>
    <div class='row py-1'>
      <div class="col-auto md-2 mx-auto">
        <p class="footer">利用規約</p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_admin_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-light py-4">
    <%= link_to "Popularize a Books", admin_books_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ml-auto">
        <% if admin_signed_in? %>
          <li>
            <%= link_to admin_members_path,class: 'nav-link text-black  mr-3 ml-3 ml-3' do %>
              <i class="fas fa-home"></i> ホーム
            <% end %>
          </li>
          <li>
            <%=  link_to admin_members_path,class: 'nav-link text-black mr-3 ml-3' do %>
              <i class="fas fa-users"></i> メンバーリスト
            <% end %>
          </li>
          <li>
            <%=  link_to admin_books_path ,class: 'nav-link text-black mr-3 ml-3' do %>
              <i class="fas fa-book-open"></i> 投稿一覧
            <% end %>
          </li>
          <li>
            <%=  link_to admin_genres_path ,class: 'nav-link text-black mr-3 ml-3' do %>
              <i class="fas fa-dna"></i> ジャンル一覧
            <% end %>
          </li>
          <li>
            <%= link_to destroy_admin_session_path, method: :delete,class: 'nav-link text-black mr-3 ml-3' do %>
              <i class="fas fa-sign-out-alt"></i> ログアウト
            <% end %>
          </li>
        <% else %>
          <li>
            <%= link_to new_admin_session_path ,class: 'nav-link text-black mr-3 ml-3' do %>
              <i class="fas fa-sign-in-alt"></i> ログイン
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul class="list-unstyled">
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_member_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(obj.errors.count, "error") %> prohibited this obj from being saved:</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_member_footer.html.erb
<footer>
  <div class='container pt-2'>
    <div class='row'>
      <div class="col-auto mt-2 mx-auto">
        <h5 class="footer">Popularize a Books</h5>
      </div>
    </div>
    <div class='row py-1'>
      <div class="col-auto md-2 mx-auto">
        <p class="footer">利用規約</p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_member_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-light py-4">
    <%= link_to "Popularize a Books", books_path, class: "navbar-brand header" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ml-auto">
        <% if member_signed_in? %>
          <li>
            <%= link_to books_path, class: 'nav-link text-black  mr-3 ml-3 ml-3  mr-3 ml-3 ml-3'  do %>
              <i class="fas fa-home"></i> ホーム
            <% end %>
          </li>
          <li>
            <%=  link_to members_path,class: 'nav-link text-black  mr-3 ml-3 ml-3  mr-3 ml-3 ml-3' do %>
              <i class="fas fa-users"></i> メンバーリスト
            <% end %>
          </li>
          <li>
            <%=  link_to books_path ,class: 'nav-link text-black  mr-3 ml-3 ml-3  mr-3 ml-3 ml-3' do %>
              <i class="fas fa-book-open"></i> 投稿一覧
            <% end %>
          </li>
          <li>
            <%=  link_to books_search_path ,class: 'nav-link text-black  mr-3 ml-3 ml-3  mr-3 ml-3 ml-3' do %>
              <i class="fas fa-book"></i> 新規投稿
            <% end %>
          </li>
          <li>
            <%= link_to member_path(current_member.id),class: 'nav-link text-black  mr-3 ml-3 ml-3  mr-3 ml-3 ml-3' do %>
              <i class="fas fa-home"></i> マイページ
            <% end %>
          </li>
          <li>
            <%= link_to destroy_member_session_path, method: :delete,class: 'nav-link text-black  mr-3 ml-3 ml-3  mr-3 ml-3 ml-3' do %>
              <i class="fas fa-sign-out-alt"></i> ログアウト
            <% end %>
          </li>
        <% else %>
          <li>
            <%= link_to root_path,class: 'nav-link text-black  mr-3 ml-3 ml-3' do %>
              <i class="fas fa-home"></i> ホーム
            <% end %>
          </li>
          <li>
            <%= link_to about_path,class: 'nav-link text-black  mr-3 ml-3 ml-3' do %>
              <i class="fas fa-link"></i> サイト紹介
            <% end %>
          </li>
          <li>
            <%= link_to new_member_registration_path,class: 'nav-link text-black  mr-3 ml-3 ml-3' do %>
              <i class="fas fa-user-plus"></i> 新規登録
            <% end %>
          </li>
          <li>
            <%= link_to new_member_session_path ,class: 'nav-link text-black  mr-3 ml-3 ml-3' do %>
              <i class="fas fa-sign-in-alt"></i> ログイン
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <script src="https://kit.fontawesome.com/e45f6b53f0.js" crossorigin="anonymous"></script>
    <title>Popularize a Books</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if request.fullpath.include? "admin" %>
      <%= render 'layouts/admin_header' %>
    <% else%>
      <%= render 'layouts/member_header' %>
    <% end %>
    <main>
      <% unless notice.nil? %>
        <p class="alert text-center"><%= notice %></p>
      <% end %>
      <%= yield %>
    </main>
    <% if request.fullpath.include? "admin" %>
      <%= render 'layouts/admin_footer' %>
    <% else%>
      <%= render 'layouts/member_footer' %>
    <% end %>
  </body>
</html>